### ISSUE TITLE
prioritization_fee_lamports field missing in TransactionConfig

### ISSUE THREAD

**Issue by AC4G** [jup-ag/jupiter-api-rust-example#6]
In https://station.jup.ag/docs/apis/troubleshooting the guide mentions prioritizationFeeLamports and dynamicComputeUnitLimit field for the /swap api endpoint but this sdk has no such config fields in the TransactionConfig struct.

**Comment by sasiyaluba** [comment]
i cannot use PrioritizationFeeLamports enum's PriorityLevelWithMaxLamports and JitoTipLamports
